name: nombre_de_tu_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+6 # Recuerda incrementar este número para tu próxima subida a TestFlight

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Paquetes base
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.13
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.0.0
  intl: ^0.18.0
  percent_indicator: ^4.2.2
  share_plus: ^7.2.2

  # Paquetes para el lector ePub
  path_provider: ^2.0.11

  # Paquetes para Notificaciones
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  
  # ¡NUEVO PAQUETE PARA HACER LLAMADAS!
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/libro_azul.pdf
    - assets/12_pasos.pdf
    - assets/12_tradiciones.pdf
    - assets/daily_readings.json
    - assets/images/daily_reflections_bg.png
    - assets/images/big_book_bg.png
    - assets/images/steps_traditions_bg.png
    - assets/images/journal_bg.png
    - assets/images/support_bg.png
    - assets/images/my_story_bg.png
    - assets/libro_azul.epub
    - assets/libro_azul_content.json

  fonts:
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/times new roman.ttf
        - asset: assets/fonts/times new roman bold.ttf
          weight: 700
        - asset: assets/fonts/times new roman italic.ttf
          style: italic
        - asset: assets/fonts/times new roman bold italic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/mi_logo.png"
  adaptive_icon_background: "#546E7A"
